source 'https://github.com/QoCHealth/external-library-ios-cocoapods-podspecs.git'

target 'Example' do
   platform :ios, '7.0'

   pod 'QoCCalendar', :path=> '/Users/kenneth.yip/development/ios/external-library-ios-Calendar/'

end
